### ISSUE TITLE
legGeometry Points are not displayed on the maps (just straight lines from stop to stop)

### ISSUE THREAD

**Issue by amenk** [opentripplanner/otp-react-redux#119]
We have a OTP 1.4.0 running and I tried otp-react-redux.

While the OTP frontend itself shows the routes aligned to the streets, the OTP-React-Redux frontend instead displays straight lines.

I believe the information is in itineraries.0.legs.0.legGeometry 

How can this be displayed?

Is this a missing feature, a bug or a misconfiguration on my side?

**Comment by mpaine-act** [comment]
I'm surprised no one has answered you yet, we are seeing same issue here.

**Comment by landonreed** [comment]
Hi @amenk and @mpaine-act, this is definitely not a missing feature. The otp-react-redux library is designed to show itinerary details as an overlay on the map. It might be helpful if you verify how you are running/building the front end and post configuration details (minus any sensitive information).

**Comment by mpaine-act** [comment]
@landonreed Maybe we are talking about different things.  I was speaking about leg shapes on the map.   For example, [OTP RR (top) and OTP default (bottom)](http://actransit.org/wp-content/uploads/OTPRRLeg.png) demonstrates my point.

**Comment by landonreed** [comment]
@mpaine-act, the issue appears to be with the version of OTP that you are running. otp-react-redux was developed and tested with the IBI fork of OpenTripPlanner (it has not been tested with 1.3.0 or 1.4.0). Much of the code we developed has made its way back to the main OTP repo, but some of it has not yet been released (partially due to the relatively slow release cycle for OTP). The leg objects need the `interStopGeometry` in order to render correctly in otp-rr. The changes that handle this can be seen in [`GraphPathToTripPlanConverter`](https://github.com/opentripplanner/OpenTripPlanner/pull/2664/files#diff-2900971deb3daeebed94c4c1f3ce824c).

The best way to fix this would probably be to just use the [ibi-dev branch](https://github.com/ibi-group/OpenTripPlanner/) of OTP until we are able to merge those changes in.
