### ISSUE TITLE
Information about including the React-Redux OTP library in Djanjo

### ISSUE THREAD

**Issue by pacoscan** [opentripplanner/otp-react-redux#276]
Can i ask you how could I use this RR library as frontend to an application with Django Backend?

**Comment by landonreed** [comment]
Hi, apologies for the delayed response. This library is intended as a user interface for the OpenTripPlanner API (version 1.x), which runs as a Java application: https://github.com/opentripplanner/OpenTripPlanner. You can also use it with [this project](https://github.com/ibi-group/otp-middleware/); however, this is not recommended at the moment because it is under heavy development.

I'm not sure exactly how you were thinking of hooking it up with a Django Backend, but that would likely require a lot of custom development that is probably out of scope for this project.
